aws emr create-cluster --applications Name=Hadoop Name=Sqoop Name=HBase Name=Spark Name=Hive
--tags 'Service=quercus-db' 'CostCenter=11998' 'POC=RD-Operations-Elevate@ellucian.com' 'Name=quercus-prod-eu'
--ec2-attributes '{"InstanceProfile":"EMR_EC2_DefaultRole","SubnetId":"subnet-2c9b0b74","EmrManagedSlaveSecurityGroup":"sg-071dbcba6f3b9b8b0","EmrManagedMasterSecurityGroup":"sg-0e165197acbca43ac"}'
--release-label emr-5.28.0 --log-uri 's3n://aws-logs-344769278604-eu-west-1/elasticmapreduce/'
--steps'[
{"Args":["s3://sqoop-script1/mkdir-script.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://sqoop-script1/copy-key-eu.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://sqoop-script1/chmod-key-eu.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/addToKnwnHost-lst-nonprod.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/copy-lst-nonprod-db-query.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/dashboard-a.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/dashboard-b.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/dashboard-c.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/dashboard-d.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/dashboard-e.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/dashboard-f.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/dashboard-g.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/dashboard-h.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/dashboard-i.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/dashboard-ja-mkdir-test.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/lst/dashboard-jb2delete-output.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["/mnt/var/lib/hadoop/steps/script/lst-nonprod-db-query.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/lst/g1-mkdir.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/lst/g2-download.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/lst/g3-merged.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/lst/g31-cut.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/lst/g32-header.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"},
{"Args":["s3://ellucian-qe-eu/sqoop-scripts/lst/g4-upload.sh"],"Type":"CUSTOM_JAR","ActionOnFailure":"CONTINUE","Jar":"s3://eu-west-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Name":"Custom JAR"}]'
 --instance-groups '[{"InstanceCount":1,"InstanceGroupType":"MASTER","InstanceType":"m3.xlarge","Name":"Master - 1"}]' --auto-terminate --auto-scaling-role EMR_AutoScaling_DefaultRole --service-role EMR_DefaultRole --enable-debugging --name 'lst-nonprod-attendance-module' --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region eu-west-1
